---
abstract: 'POEditor.com API wrapper'
author:
  - 'Roman F. <romanf@cpan.org>'
build_requires:
  Test::Most: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-POEditor
requires:
  Moose: 0
  MooseX::Attribute::ENV: 0
  Role::REST::Client: 0
  namespace::clean: 0
  version: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=WebService-POEditor
  repository: git://github.com/moltar/WebService-POEditor.git
version: v1.0.0
